# Generated by Django 5.1.7 on 2025-04-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_image', models.ImageField(null=True, upload_to='componentes/imagens/')),
                ('reference_location', models.CharField(max_length=255)),
                ('datasheet', models.FileField(null=True, upload_to='componentes/datasheets/')),
            ],
            options={
                'db_table': 'componentes',
            },
        ),
    ]
