# Generated by Django 5.1.7 on 2025-03-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(help_text='Termo que o usuário digitou no campo de busca.', max_length=255)),
                ('found', models.BooleanField(default=False, help_text='Indica se a busca retornou ao menos um resultado.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a busca foi registrada.')),
                ('component', models.ForeignKey(blank=True, help_text='Referência ao componente encontrado, se for um único item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.component')),
            ],
        ),
    ]
